# Generated by Django 5.2.17 on 2026-10-02 07:38

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_no', models.CharField(max_length=50, unique=True)),
                ('full_name', models.CharField(max_length=150)),
                ('father_name', models.CharField(max_length=150)),
                ('cnic', models.CharField(max_length=50)),
                ('dob', models.DateField(default=datetime.date(2006, 1, 1))),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField()),
                ('matric_board', models.CharField(default='BISE Gujranwala', max_length=100)),
                ('matric_roll', models.CharField(max_length=50)),
                ('matric_obtained', models.FloatField()),
                ('matric_total', models.FloatField(default=1100.0)),
                ('inter_board', models.CharField(blank=True, default='BISE Gujranwala', max_length=100)),
                ('inter_roll', models.CharField(blank=True, max_length=50)),
                ('inter_obtained', models.FloatField(default=0.0)),
                ('inter_total', models.FloatField(default=1100.0)),
                ('applied_program', models.CharField(max_length=150)),
                ('is_hafiz', models.BooleanField(default=False)),
                ('aggregate_merit', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('shortlisted', 'Merit Shortlisted'), ('admitted', 'Admitted / Fee Paid'), ('rejected', 'Disqualified / Rejected')], default='submitted', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_addressed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Contact Inquiries',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FeeChallan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challan_no', models.CharField(max_length=50, unique=True)),
                ('student_name', models.CharField(max_length=150)),
                ('roll_or_app_no', models.CharField(max_length=50)),
                ('program', models.CharField(max_length=150)),
                ('amount', models.DecimalField(decimal_places=2, default=14500.0, max_digits=10)),
                ('issue_date', models.DateField(default=django.utils.timezone.now)),
                ('due_date', models.DateField()),
                ('is_paid', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('admissions', 'Admissions'), ('merit', 'Merit Lists'), ('examinations', 'Examinations'), ('scholarships', 'Scholarships'), ('sports', 'Sports & Co-curricular'), ('general', 'General Notification')], default='general', max_length=50)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('is_urgent', models.BooleanField(default=False)),
                ('summary', models.TextField()),
                ('details', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='notices/')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.CharField(help_text='e.g. BSCS-22-10', max_length=50, unique=True)),
                ('registration_no', models.CharField(max_length=100, unique=True)),
                ('full_name', models.CharField(max_length=150)),
                ('father_name', models.CharField(max_length=150)),
                ('program', models.CharField(max_length=150)),
                ('current_semester', models.PositiveIntegerField(default=1)),
                ('cgpa', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='FacultyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('role', models.CharField(help_text='e.g. Principal, Head of Department, Associate Professor', max_length=150)),
                ('qualification', models.CharField(max_length=255)),
                ('experience', models.CharField(max_length=100)),
                ('specialization', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('image', models.CharField(default='assets/images/principal.svg', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faculty', to='portal.department')),
            ],
            options={
                'verbose_name_plural': 'Faculty Members',
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('level', models.CharField(choices=[('bs', 'BS (4-Year) Honors'), ('intermediate', 'Intermediate (HSSC)'), ('adp', 'Associate Degree (ADP)')], default='bs', max_length=30)),
                ('duration', models.CharField(default='4 Years (8 Semesters)', max_length=100)),
                ('affiliation', models.CharField(default='University of the Punjab', max_length=150)),
                ('eligibility', models.CharField(max_length=255)),
                ('seats', models.PositiveIntegerField(default=50)),
                ('description', models.TextField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='portal.department')),
            ],
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(help_text='e.g. 4th Semester (Spring 2026)', max_length=50)),
                ('course_code', models.CharField(max_length=50)),
                ('course_title', models.CharField(max_length=150)),
                ('credit_hours', models.CharField(default='3+1', max_length=20)),
                ('marks_obtained', models.FloatField()),
                ('total_marks', models.FloatField(default=100.0)),
                ('grade', models.CharField(max_length=5)),
                ('grade_point', models.FloatField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='portal.student')),
            ],
        ),
    ]
