services:
  - type: web
    name: ggc-hafizabad
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn ggc_hafizabad.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: DJANGO_SETTINGS_MODULE
        value: ggc_hafizabad.settings
      - key: DEBUG
        value: "True"
